### ISSUE TITLE
Open APIとcommitee-railsを導入する

### ISSUE THREAD

**Issue by ochi-sho-private-study** [Progaku-copy/progaku-archive#32]
## ゴール
- Open APIを書く。
- commitee-railsを導入して、テストに反映する。

## 参考
- https://github.com/willnet/committee-rails
- https://zenn.dev/overflow_offers/articles/20220802-committee-rails

**Comment by rikuya98** [comment]
@ochi-sho-private-study 
一点質問です。
OpenAPIのリクエストパラメーターのデータ形式の定義はjsonで良いでしょうか？
commiteeで検証する際にOpenAPIの定義に合わせて、Rspecでリクエストを送る際にデータ形式を指定しないと行けなくて。
確認させていただきたいです！
