### ISSUE TITLE
メモのタグを表現できるようにする

### ISSUE THREAD

**Issue by ochi-sho-private-study** [Progaku-copy/progaku-archive#33]
## 背景
- メモの作成・更新時にタグをつけたい。
  - `ruby`・`rails`・`typescript`・`就活の面接`など。
- メモに対して、複数のタグを紐づけられるようにする。

## ゴール
- メモのタグを表現できるようにテーブルを追加する。
- メモのタグを単体で作成・更新できるAPIを作成する。

**Comment by Shunsuke2967** [comment]
@ochi-sho-private-study 
すみませんこちらの「メモのタグを単体で作成・更新できるAPI」というのはエンドポイントを追加してそこを叩くことでタグが作られるようにするという認識であっていますでしょうか？
お手数ですがご確認お願いします。

**Comment by ochi-sho-private-study** [comment]
@Shunsuke2967 

> すみませんこちらの「メモのタグを単体で作成・更新できるAPI」というのはエンドポイントを追加してそこを叩くことでタグが作られるようにするという認識であっていますでしょうか？

はい、メモのタグのリソースを扱うエンドポイントを追加すると言う意味で合っています。

> 「単体で」がどのような事柄を指すのか理解できませんでした。

「メモのタグを単体で」というのは、
メモのタグ、というリソース自体のことを指しています！
例えば、メモのタグのリソースが、memo_tagsというリソース名だとしたら、
MemoTagsControllerクラスにcreateアクションとupdateアクションが生えるイメージです！
