### ISSUE TITLE
無料でできる、バックエンドのインフラ構成を考える

### ISSUE THREAD

**Issue by kakeru-one** [Progaku-copy/progaku-archive#37]
## ゴール
- 無料でできる、バックエンドのインフラ構成を考える。
  - AWSやGCPはなし。Renderとか良さそう。

**Comment by ochi-sho-private-study** [comment]
DBは専用のインフラを用意すると、無料では期限付きで出ないと実現出来なさそうなので、
Linuxサーバーを用意してそこにRDBMSをインストールする形がいいかも
