### ISSUE TITLE
ユーザ認証機能の実装

### ISSUE THREAD

**Issue by kuri0616** [Progaku-copy/progaku-archive#73]
### Userテーブルの定義変更
* パスワードダイジェストカラムの作成
* Adminカラムの作成
* ユーザ名、パスワードのバリデーションの追加
* ユーザ名、パスワードのカラムの定義変更(Byte数など最適化する)

### UserのAPI作成(CRUD)
* 管理者のみ作成可能にする

### 認証APIの作成
* Sessionコントローラーを作成
* Cookieが使用できるようにミドルウェアや設定を追加する

### 実装方針
* Userテーブルのパスワードカラムをパスワードダイジェストカラムに変更する
* User作成時、パスワードをハッシュ関数でハッシュ化してダイジェストカラムに保存する
https://github.com/bcrypt-ruby/bcrypt-ruby
* 認証時は、受け取ったパスワードをハッシュ化　DBのダイジェストカラムと比較する
* session_controllerを作成する
* session_cookie方式で実装する

**Comment by ochi-sho-private-study** [comment]
## 調べたいこと
- bcryptではどのようにパスワードが暗号化されているのか？
- sessionメソッドはどのように動作するのか？

**Comment by rikuya98** [comment]
調べること
* session_controllerの実装方法

**Comment by rikuya98** [comment]
## モデルのテスト観点

### モデルの定義
```
  validates :account_name, presence: true, uniqueness: true, length: { minimum: 6, maximum: 30 }
  validates :password, presence: true, length: { minimum: 6, maximum: 12 }
```

### account_name
* 必須チェック
* 一意制約チェック
* lengthチェック6文字以上、30文字以下

### password
* 必須チェック
* lengthチェック6文字以上、12文字
