### ISSUE TITLE
メモテーブルにSlackの投稿者名を入れるユーザ名のカラムを追加する

### ISSUE THREAD

**Issue by kuri0616** [Progaku-copy/progaku-archive#89]
* Slackの文字数制限に合わせてVARCHARで21文字で定義する
* 必須項目にする

**Comment by ochi-sho-private-study** [comment]
@kuri0616 
検索時に使えるように、チャンネル名もあった方がいいかもしれないですね！

**Comment by kuri0616** [comment]
@ochi-sho-private-study 
確かにあったほうが良さそうですね！
ただ一旦、フロント側のことも考慮して、リリースまではチャンネル名は無で行きますね😭
